### ISSUE TITLE
when i uploaded yii2-fancybox3 to server then found error

### ISSUE THREAD

**Issue by jamespakorn** [newerton/yii2-fancybox-3#9]
![xx3](https://user-images.githubusercontent.com/17809231/34187717-58aaa1e0-e565-11e7-9b06-6518155e970d.jpg)

**Comment by newerton** [comment]
What your version of PHP and Yii?

**Comment by jamespakorn** [comment]
### Yii 2.0.13.1  PHP 5.4.45

![y](https://user-images.githubusercontent.com/17809231/34237627-5246b5b6-e630-11e7-96db-ece428b9b1f9.jpg)

**Comment by newerton** [comment]
Requirement:
![image](https://user-images.githubusercontent.com/4175945/34249668-abc742ea-e621-11e7-9bc8-25f28279cae0.png)

![image](https://user-images.githubusercontent.com/4175945/34249690-c319f528-e621-11e7-92e4-ec281ef51018.png)

**Comment by jamespakorn** [comment]
## i have temporary solving this problem by 
```
<?php
/**
 * @copyright Copyright (c) 2017 Newerton Vargas de Araújo
 * @link http://newerton.com.br
 * @license http://www.opensource.org/licenses/bsd-license.php New BSD License
 */
namespace newerton\fancybox3;

use yii\web\AssetBundle;

class FancyBoxAsset extends AssetBundle
{
    public $sourcePath = '@bower/fancybox';

    public $css = [
        // 'dist/jquery.fancybox' . (!YII_DEBUG ? '.min' : '') . '.css'
        'dist/jquery.fancybox.min'
    ];

    public $js = [
        // 'dist/jquery.fancybox' . (!YII_DEBUG ? '.min' : '') . '.js'
        'dist/jquery.fancybox.js'
    ];

    public $depends = [
        'yii\web\JqueryAsset',
    ];
}

**Comment by newerton** [comment]
Update your php version.
